CC := armv5tel-cacko-linux-gcc
CXX := arm-cacko-linux-gnu-g++
AR := armv5tel-cacko-linux-ar

QTDIR ?= /opt/Qtopia/qt-2.3.2
QPESDK ?= /opt/murphytalk-sdk/qtopia-free-1.7.0

SIMAVR := third_party/simavr
SIM_INC := -I$(SIMAVR) -I$(SIMAVR)/sim -I$(SIMAVR)/examples/parts
CPPFLAGS += -Iinclude -Isrc $(SIM_INC) -I$(QPESDK)/include -I$(QTDIR)/include

COMMON_CFLAGS := -pipe -O2 -Wall -W -DQT_QWS_SL5XXX -DQT_QWS_CUSTOM -DQWS -DQT_NO_PROPERTIES -DQT_NO_DRAGANDDROP -DNO_DEBUG
CFLAGS := $(COMMON_CFLAGS) -std=gnu99 -mcpu=xscale -mhard-float
CXXFLAGS := $(COMMON_CFLAGS) -fno-exceptions -fno-rtti
LDFLAGS :=
LDLIBS := -Wl,--allow-shlib-undefined -Llib -L$(QTDIR)/lib -lqpe -lqte -lm

SIM_SRCS := \
	$(SIMAVR)/cores/sim_mega32u4.c \
	$(SIMAVR)/sim/avr_acomp.c \
	$(SIMAVR)/sim/avr_adc.c \
	$(SIMAVR)/sim/avr_eeprom.c \
	$(SIMAVR)/sim/avr_extint.c \
	$(SIMAVR)/sim/avr_flash.c \
	$(SIMAVR)/sim/avr_ioport.c \
	$(SIMAVR)/sim/avr_spi.c \
	$(SIMAVR)/sim/avr_timer.c \
	$(SIMAVR)/sim/avr_twi.c \
	$(SIMAVR)/sim/avr_uart.c \
	$(SIMAVR)/sim/avr_usb.c \
	$(SIMAVR)/sim/avr_watchdog.c \
	$(SIMAVR)/sim/sim_avr.c \
	$(SIMAVR)/sim/sim_cmds.c \
	$(SIMAVR)/sim/sim_core.c \
	$(SIMAVR)/sim/sim_cycle_timers.c \
	$(SIMAVR)/sim/sim_gdb.c \
	$(SIMAVR)/sim/sim_interrupts.c \
	$(SIMAVR)/sim/sim_io.c \
	$(SIMAVR)/sim/sim_irq.c \
	$(SIMAVR)/sim/sim_utils.c \
	$(SIMAVR)/sim/sim_vcd_file.c \
	$(SIMAVR)/examples/parts/ssd1306_virt.c

CORE_SRCS := src/hex_loader.c src/arduboy_core.c src/compat_gcc.c
OBJS := $(SIM_SRCS:.c=.o) $(CORE_SRCS:.c=.o)

.PHONY: all clean

all: zaurusarduboy

libzaurusarduboy.a: $(OBJS)
	$(AR) rcs $@ $(OBJS)

zaurusarduboy: src/zaurus_qt_main.o libzaurusarduboy.a
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -o $@ src/zaurus_qt_main.o libzaurusarduboy.a $(LDLIBS)

clean:
	rm -f $(OBJS) src/zaurus_qt_main.o libzaurusarduboy.a zaurusarduboy
